### ISSUE TITLE
React is installed as dependency despite peer-dependency setting

### ISSUE THREAD

**Issue by chriszrc** [iamskok/use-font-face-observer#147]
When I install this package, react shows up in use-font-face-observer/node_modules  and I get the hook errors because of it-

**Comment by edward93** [comment]
https://github.com/iamskok/use-font-face-observer/blob/master/package.json#L32
I believe this shouldn't be there, correct?

**Comment by chriszrc** [comment]
@edward93 yes, exactly, it's already in the peer dependencies-

**Comment by edward93** [comment]
@chriszrc I'm very much tempted to submit a PR but unsure a bit! There are several open PRs already and I didn't see "contribution guide" or anything of that sort so I'm hesitating.

**Comment by ileccese** [comment]
+1 on this issue

**Comment by oleksandr-danylchenko** [comment]
+1 on the issue 🙏🏻

**Comment by oleksandr-danylchenko** [comment]
UPD: Added the #158 PR that should resolve this issue 👌🏻

**Comment by iamskok** [comment]
The fix was merged and released as v1.2.2
