### ISSUE TITLE
Typescript typings dont work with bundler moduleResolution

### ISSUE THREAD

**Issue by steelbrain** [iamskok/use-font-face-observer#169]
Hello!

Thanks for making this package! It seems that typings are broken when tsconfig sets module resolution to bundler. Here's a repository with a reproduction: https://github.com/steelbrain/bug-reproduction-2024-10-use-font-face-observer

Here's the error message

> There are types at 'bug-reproduction-2024-10-use-font-face-observer/node_modules/use-font-face-observer/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'use-font-face-observer' library may need to update its package.json or typings.

**Comment by artemis-prime** [comment]
Why is this marked as closed / completed?  Is there some workaround or?

**Comment by iamskok** [comment]
@artemis-prime it should be fixed by #170

**Comment by steelbrain** [comment]
It's merged in but still unreleased on npm, hence the confusion I believe

**Comment by iamskok** [comment]
@steelbrain @artemis-prime The repo is set up to automatically release NPM packages via semantic-release, which relies on a specific commit message format (see relevant docs). I missed this during the review, but I’ve merged another PR that should trigger a release. Please check and let me know if it worked this time.
